### ISSUE TITLE
Feature: User can view a list of anime in order by genre

### ISSUE THREAD

**Issue by kaitlin-lovrich** [kaitlin-lovrich/Popular-Anime-Viewer#1]
## ⚙️ Feature

> User can view a list of popular anime separated by genre

## 📐 Functionality

> Scroll vertically through genre labeled rows 
> Scroll horizontally on the row containing anime titles

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="506" alt="Screenshot 2023-10-05 150353" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/5ae137f4-b73d-4d61-82ea-17e3fb172a2f">

<img width="211" alt="Screenshot 2023-10-05 150303" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/368ad6ed-720d-424b-98fe-f5ea94f1b29f">

## ✅ Task List

> #

#### Commit checklist for tasks needed to complete the feature.

- [x] Add an HTML skeleton
- [x] In the `<head>` element, add:
  - [x] Add a `<link>` to styles.css
  - [x] Add a `<link>` to font awesome
- [x] In `<main>` add a `<div>` with a class of 'container'. Everything from here on will be inside this container
- [x] Add a `<div>` to contain the page's header, to that `<div>`, add:
  - [x] An `<h1>` tag containing the page title name 
  - [x] An anchor tag `<a>` for each page navigation: 'HOME, TV SHOWS, MOVIES, MY FAVORITES'
  - [x] A search `<input>` element with a `<label>` for="search" `<input>` with an id="search" name="search" placeholder="fa-magnifying-glass Search Title"
  - [x] In styles.css, style the header to look like the figma
- [x] In index.html below the header, add a `<div>`, inside:
  - [x] Add two empty `<ul>` elements, the second with an id of #titles, these will be the rows
  - [x] Create 2 dummy anime title images, one to go in each `<ul>` as an `<li>` element. This is to simulate  the first title image element in the list in each of the 2 rows. Don't forget the verticle ellipse overlaying the title image on the top right corner
- [x] Style the Home page like the figma in styles.css
- [x] In main.js, query for the #titles `<ul>`.
- [x] Write a function `renderTitles(title)` that will take in a title and create a `<li>` element of that title's image along with the overlay ellipse and return that li element. The title parameter represents a single object anime title from a query array. The function should generate and return a DOM tree for a single title in the #titles `<ul>`
- [x] Get popular anime data using `XMLHttpRequest`:
  - [x] Create a new `xhr` object using `new XHMLHttpRequest( )`
  - [x] `xhr.open('GET', <url> )` to set the request method and URL 
  - [x] `xhr.responseType = 'json'` to automatically parse the JSON response body into JavaScript objects.
  - [x] `xhr.addEventListener('load', <funtion> )` to execute a function when the response is loaded.
    - [x] The function should log `xhr.status` and `xhr.response`
    - [x] `Loop` through the `titles` and create a `DOM tree` for each `title` utilizing the `renderTitles(title)` function and append each DOM tree to the #titles `<ul>`
  - [x] `xhr.send` to send the request to the server at the URL specified in `xhr.open`
-[ ] Remove the example HTML titles from index.html once the titles are successfully being appended to the DOM on page load
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
