### ISSUE TITLE
Feature: User can filter anime titles by ‘tv’ or ‘movie’

### ISSUE THREAD

**Issue by kaitlin-lovrich** [kaitlin-lovrich/Popular-Anime-Viewer#3]
## ⚙️ Feature

> User can filter anime titles by ‘tv’ or ‘movie’

## 📐 Functionality

> User will be able to filter anime titles on the home page to only show either TV Show or Movie categories

## 🖼️ Wireframes

> ##### 

><img width="389" alt="Screenshot 2023-10-05 162234" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/7ee23191-bac0-4478-814c-5e050277b6e8">

><img width="194" alt="Screenshot 2023-10-05 162518" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/f5be4b98-c3a7-4dfe-a8f0-bf87c0fb4087">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] query for home tv shows and movies buttons
- [x] add event handlers to each button to show the appropriate view
  - [x] modify the getGenreId function to conditionally  filter out tv or movies if the buttons are clicked
  - [x] modify the button that was clicked to show it is 'active'
  - [x] if the home button is clicked, show both tv and movie shows and reset the category button that was activated
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
