### ISSUE TITLE
Feature: User can search anime by name #3

### ISSUE THREAD

**Issue by kaitlin-lovrich** [kaitlin-lovrich/Popular-Anime-Viewer#5]
## ⚙️ Feature

> User can search anime by name

## 📐 Functionality

> User will click on the search bar (or magnifying glass in mobile view) and type in the title of the anime they wish to view, the app will return titles images that match the search input

## 🖼️ Wireframes

> <img width="512" alt="search desktop view" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/79f97eec-c5b4-4450-a605-b8233e14ffdc">

> <img width="276" alt="ajax search home view" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/bbf489e7-ee7b-4126-922c-8615dfa306ef">

> <img width="278" alt="ajax search mobile view" src="https://github.com/kaitlin-lovrich/Popular-Anime-Viewer/assets/69818777/759b55b6-94e3-4c5b-bc2a-11bd87cc9373">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Query for search input and magnifying glass icon
- [x] When user clicks search input or magnifying glass:
  - [x] Clear the #titles div's innerHTML
  - [x] Give the #titles div a new empty row labeled search results
  - [x] Give the titles div a second row labeled popular picks and render a row with popular title images
  - [x] Style the search desktop page 
  - [x] Style the search mobile page, get rid of footer
  - [x] Query for left arrow on search page mobile and have it return to data.lastView when clicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
